"""Pi 5 servos, ultrasonic sensor, and one direct active-low pump relay.

Importing this module does not claim pins. See DIRECT_GPIO.md.
"""

import grp
import os
from pathlib import Path
import threading
import time

from weight_sensor import open_header


GATE_GPIO = 18  # Physical 12, RP1 PWM0 channel 2
SORT_GPIO = 19  # Physical 35, RP1 PWM0 channel 3
RELAY1_GPIO = 22  # Physical 15; GPIO17 is already the green button
RELAY_ON = 0  # Direct module input: LOW energizes channel 1.
RELAY_OFF = 1
TRIG_GPIO = 23  # Physical 16
ECHO_GPIO = 24  # Physical 18, AFTER the 330/470 ohm divider
CONTROL_PINS = {GATE_GPIO, SORT_GPIO, RELAY1_GPIO, TRIG_GPIO, ECHO_GPIO}


def find_pwm_chip(root=Path("/sys/class/pwm")):
    """Select RP1 PWM0 by device-tree identity, never the fan's PWM1 chip."""
    for chip in sorted(root.glob("pwmchip*")):
        node = chip / "device/of_node"
        if (node.resolve().name == "pwm@98000"
                and b"raspberrypi,rp1-pwm" in (node / "compatible").read_bytes()):
            return chip
    raise RuntimeError(
        "RP1 PWM0 not found. Add dtoverlay=pwm-2chan under [all] in "
        "/boot/firmware/config.txt, then reboot. See DIRECT_GPIO.md."
    )


def prepare_pwm():
    """Explicit root-only setup, once per boot, with the controller stopped."""
    if os.geteuid() != 0:
        raise PermissionError("Run --prepare-pwm with sudo, while the controller is stopped.")
    chip = find_pwm_chip()
    group = grp.getgrnam("gpio").gr_gid
    for channel in (2, 3):
        path = chip / f"pwm{channel}"
        if not path.exists():
            (chip / "export").write_text(str(channel))
        deadline = time.monotonic() + 2
        while not (path / "enable").exists():
            if time.monotonic() >= deadline:
                raise RuntimeError(f"PWM export did not create {path}")
            time.sleep(0.01)
        for name in ("enable", "period", "duty_cycle", "polarity"):
            target = path / name
            os.chown(target, -1, group)
            os.chmod(target, 0o660)
    return chip


class HardwareServo:
    """50 Hz PWM generated by RP1 hardware, not a Python timing thread."""

    def __init__(self, chip, channel):
        self.path = chip / f"pwm{channel}"
        if not (self.path / "enable").exists():
            raise RuntimeError("Run sudo python3 direct_gpio.py --prepare-pwm after boot.")
        self.write("enable", 0)
        self.write("duty_cycle", 0)
        self.write("polarity", "normal")
        self.write("period", 20_000_000)

    def write(self, name, value):
        (self.path / name).write_text(str(value))

    def pulse(self, microseconds):
        if not 500 <= microseconds <= 2500:
            raise ValueError("Servo pulse must be between 500 and 2500 microseconds.")
        self.write("duty_cycle", round(microseconds * 1000))
        self.write("enable", 1)

    def close(self):
        self.write("enable", 0)


class PiGPIOHardware:
    def __init__(self):
        self.gpio = None
        self.handle = None
        self.outputs = []
        self.servos = {}
        self.callback = None
        self.io_lock = threading.RLock()
        self.echo_lock = threading.Lock()
        self.echo_done = threading.Event()
        self.armed_at = None
        self.rise_at = None
        self.width_ns = None

    def open(self):
        import lgpio

        self.gpio = lgpio
        try:
            self.handle = open_header(lgpio)
            # Request the relay OFF atomically; a LOW startup value runs the pump.
            # Channel 2 is unused and has no Pi GPIO connection.
            for pin, initial in ((RELAY1_GPIO, RELAY_OFF), (TRIG_GPIO, 0)):
                lgpio.gpio_claim_output(self.handle, pin, initial)
                self.outputs.append(pin)
            chip = find_pwm_chip()
            for name, channel in (("gate", 2), ("sort", 3)):
                self.servos[name] = HardwareServo(chip, channel)
            lgpio.gpio_claim_alert(self.handle, ECHO_GPIO, lgpio.BOTH_EDGES)
            self.callback = lgpio.callback(
                self.handle, ECHO_GPIO, lgpio.BOTH_EDGES, self._echo_edge,
            )
        except BaseException:
            self.close()
            raise

    def servo(self, name, microseconds):
        with self.io_lock:
            self.servos[name].pulse(microseconds)

    def pump(self, enabled):
        with self.io_lock:
            if self.handle is None:
                if enabled:
                    raise RuntimeError("GPIO hardware is closed.")
                return
            self.gpio.gpio_write(self.handle, RELAY1_GPIO, RELAY_ON if enabled else RELAY_OFF)

    def all_off(self):
        with self.io_lock:
            if self.handle is not None and RELAY1_GPIO in self.outputs:
                self.gpio.gpio_write(self.handle, RELAY1_GPIO, RELAY_OFF)

    def _echo_edge(self, chip, gpio, level, timestamp):
        # lgpio supplies kernel edge timestamps in monotonic nanoseconds.
        with self.echo_lock:
            if self.armed_at is None or timestamp < self.armed_at:
                return
            if level == 1 and self.rise_at is None:
                self.rise_at = timestamp
            elif level == 0 and self.rise_at is not None:
                self.width_ns = timestamp - self.rise_at
                self.armed_at = None
                self.echo_done.set()

    def distance_cm(self):
        return self._measure_distance_cm()

    def _measure_distance_cm(self):
        # A pre-existing HIGH or timed-out echo is invalid, never a cached distance.
        if self.gpio.gpio_read(self.handle, ECHO_GPIO):
            return None
        with self.echo_lock:
            self.echo_done.clear()
            self.rise_at = self.width_ns = None
            self.armed_at = time.monotonic_ns()
        try:
            self.gpio.tx_pulse(self.handle, TRIG_GPIO, 10, 10, 0, 1)
            self.echo_done.wait(0.06)  # Allow kernel notification delivery latency.
            with self.echo_lock:
                width = self.width_ns
            if width is None or not 100_000 <= width <= 30_000_000:
                return None
            return width / 1_000_000_000 * 34300 / 2
        finally:
            with self.echo_lock:
                self.armed_at = None

    def close(self):
        # Attempt every cleanup even if a previous GPIO/PWM write fails.
        errors = []
        with self.io_lock:
            for pin in self.outputs:
                try:
                    # TRIG uses one-shot pulses. Do not send a zero-length
                    # pulse here: some lgpio builds reject it as bad PWM micros.
                    # gpiochip_close below stops any pending transmission.
                    self.gpio.gpio_write(self.handle, pin, RELAY_OFF if pin == RELAY1_GPIO else 0)
                except Exception as error:
                    errors.append(error)
            self.outputs.clear()
            for servo in self.servos.values():
                try:
                    servo.close()
                except Exception as error:
                    errors.append(error)
            self.servos.clear()
            if self.callback is not None:
                try:
                    self.callback.cancel()
                except Exception as error:
                    errors.append(error)
                self.callback = None
            if self.handle is not None:
                try:
                    self.gpio.gpiochip_close(self.handle)
                except Exception as error:
                    errors.append(error)
                self.handle = None
        if errors:
            raise RuntimeError(f"GPIO cleanup failed: {errors}")


def create_hardware():
    """Create the direct Pi controller, including when old serial settings remain."""
    return PiGPIOHardware()
